import React, { useState, useEffect } from "react";
import { useParams } from "react-router-dom";


const ImageAttributions = () => {

    return (
        <div className="h-full bg-blue-200 p-5" >
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@homescreenify?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Homescreenify</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/spaghetti-on-white-ceramic-plate-sA3wymYqyaI?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@milkbox?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Ryan Kwok</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/bowl-of-cooked-food-H6iSwrAOMG0?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@cliffer14?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Cliffer Rebelo</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/a-delicious-caesar-salad-ready-to-be-eaten-_SUBifWXat0?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@aurel__lens?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Aurélien Lemasson-Théobald</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/round-cooked-pizza-x00CzBt4Dfk?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@ninjason?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Jason Leung</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/taco-dish-tZq8NkZ3T8k?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@genomontani?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Evgheni Russu</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/brown-pie-on-red-round-plate-xrx6_WKJyfA?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@mahmoud_fawzy100?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Mahmoud Fawzy</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/sushi-on-white-ceramic-plate-FBezBX26dyY?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@stumoffatimages?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Stu Moffat</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/burger-with-lettuce-and-tomato-Al9618AKGts?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@nate_dumlao?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Nathan Dumlao</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/white-ceramic-bowl-with-soup-beside-stainless-steel-fork-and-knife-bBmmcOISJGU?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@markuswinkler?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Markus Winkler</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/a-white-plate-topped-with-noodles-and-vegetables-29NNEOxftyg?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@will0629?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Will Porada</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/bread-sandwich-on-plate-EhkVwARHfDc?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@enginakyurt?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">engin akyurt</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/a-plate-of-food-on-a-wooden-table-Jrvcg9My0B4?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@henriquepaim?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Henrique Paim</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/two-tacos-with-meat-and-vegetables-on-a-blue-plate-Zi2fEt1XEy4?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@meganmarkham?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Megan Bucknall</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/green-soup-on-white-ceramic-bowl-qav5LFLbSUk?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@hanxiaoyaaaaa?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Hanxiao Xu</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/a-plate-of-rice-and-peas-on-a-stove-42UmsPkOETM?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@jontyson?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Jon Tyson</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/board-of-grilled-meats-kctt4tL1dkE?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@luisabrimble?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Luisa Brimble</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/sliced-tomato-and-green-leaf-vegetable-on-white-ceramic-plate-vIm26fn_QKg?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@waldemarbrandt67w?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Waldemar Brandt</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/tomato-soup-with-a-swirl-of-cream-and-greens-Ho3aLhhywuA?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@laniel?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Daniel Lee</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/white-and-brown-dish-on-black-cooking-pot-QiT06DDAXVQ?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@emanuelekstrom?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Emanuel Ekström</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/a-white-plate-topped-with-lasagna-covered-in-sauce-flEUTTwGlJQ?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@brunocervera?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">BRUNO CERVERA</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/two-quesadillas-sit-on-a-white-plate-mbVvCSkBwI8?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@kshar2?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">kiryl</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/potato-fries-DQbE7rhTC8w?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@switchinglanes?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Deepthi Clicks</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/a-bowl-of-chili-next-to-some-muffins-5j0Ir7xLeTM?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@nataliaraylenegusakova?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Natalia Gusakova</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/a-white-plate-topped-with-stuffed-bell-peppers-myfDbaJr6vA?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@itworkonline?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Jay Nlper</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/white-ceramic-plate-with-rice-and-stainless-steel-fork-XciY4hwqnNk?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@alexbayev?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Alex Bayev</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/a-bowl-of-pasta-soup-with-a-spoon-in-it-uNDgzmC5ckw?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@briewilly?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Chad Montano</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/beef-steak-with-fork-M0lUxgLnlfk?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@dtrinksrph?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">David Trinks</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/a-bowl-of-macaroni-and-cheese-with-a-spoon-in-it-sZmiZ1V41vg?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@sapporo2025?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Marco Palumbo</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/delicious-breakfast-plates-with-bagels-and-juice-D4Q1pFoDEV0?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@honeypoppet?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Sandie Clarke</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/a-bowl-of-hummus-next-to-some-garlic--ulJ5sF0NPg?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@shivsm_30?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">shibani Mishra</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/a-plate-of-pasta-with-broccoli-and-parmesan-cheese-docP-fBTnjw?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@meemeeno?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Do mee</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/clam-and-vegetable-soup-in-white-ceramic-bowl-SH8_JmrsQcw?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@mandimelanie?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Amanda Lim</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/roasted-chicken-on-black-metal-grill-e_A-SFvqV08?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@crystalsjo?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Crystal Jo</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/brown-bread-on-white-ceramic-plate-Q58N5cBKDZ8?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@don_rex?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Samuel Agyeman-Duah</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/a-slice-of-quiche-on-a-white-plate-on-a-wooden-table-ivFdoHieX08?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@snappr?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Snappr</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/a-burrito-cut-in-half-on-a-plate-BqV9zOdio6A?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@crystalsjo?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Crystal Jo</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/ramen-dish-on-brown-ceramic-bowl-TWTxHN2QIGc?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@frostyfilmsandphoto?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Mikey Frost</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/a-black-plate-topped-with-dumplings-on-top-of-a-wooden-table-klTf2RN37Ts?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@foodjetsexpress?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">logan jeffrey</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/cooked-food-on-white-ceramic-plate-CJarbDnrdfs?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
            <li>Photo by <a className={"font-bold underline text-yellow-600 hover:text-white"} href="https://unsplash.com/@victoriakosmo?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Victoria Shes</a> on <a className={"font-bold underline text-blue-500 hover:text-white"} href="https://unsplash.com/photos/stainless-steel-spoon-on-white-ceramic-bowl-90Z4qIxWc8Y?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText" target="_blank">Unsplash</a></li>
        </div>
    )
};

export default ImageAttributions;